apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

bases:
  - ../../base

nameSuffix: -prod

replicas:
  - name: http-hello-world
    count: 3

resources:
  - hpa.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: http-hello-world
      spec:
        template:
          spec:
            containers:
            - name: http-hello-world
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "200m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: http-hello-world
      spec:
        rules:
        - host: hello-world.example.com

commonLabels:
  environment: production
