apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-hello-world
  labels:
    app: http-hello-world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-qovery
  rules:
  - host: hello-world.z85acdd55.bool.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-hello-world
            port:
              name: http
