apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-hello-world
  labels:
    app: http-hello-world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hello-world.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-hello-world
            port:
              name: http
